### ISSUE TITLE
ERRO SX2

### ISSUE THREAD

**Issue by maximinocastro** [amjgfarias/pbupddistr#1]
Ao tentar processar os arquivos ZIP, apresentou os seguintes erros:

[Info  - 22:55:04] [22:55:03] ERROR: Alias does not exist SX2
           ( PREVIOUS ERROR : Alias does not exist SM0 )

CHKFILE - APLIB200.PRW(929) - Params: CALIAS:SM0,LEXCL:.F.,CNEWALIAS:NIL,BCREATEARQ:NIL,BCREATEIDX:NIL,LCREATE:NIL,LINOPENDATA:.F.,CSX2:SX2,LINDEXOPEN:.T.,LBROWSE:.F.,LVERIFYFILE:NIL )
XCHKFILE - APLIB240.PRW(429) - Params: OERROPERATION:->SM0 )
RTERRHANDLER - APLIB240.PRW(365) - Params: OERR:O )
{ |e| RtErrHandler(e) } - MATXFUNC.PRX(0) - Params: E:O )
PREPAREKEY - APLIB050.PRW(1899) - Params: CNAME:RnUpddistr,LEMPRESA:.T.,LFILIAL:.F. )
LOCKBYNAME - APLIB050.PRW(1757) - Params: CNAME:RnUpddistr,LEMPRESA:NIL,LFILIAL:NIL,LMAYIUSEDISK:.F. )
RNUPDDISTR - MONTASDFSYSTEMLOAD.PRW(509) - Params: CMSG:21-10-08-bra-helps_dif_12_1_33 )
XLISTZIP - MONTASDFSYSTEMLOAD.PRW(178) - Params: CFILE:21-10-08-bra-helps_dif_12_1_33.zip,CORIGEM:c:\tmpzip\,CDESTINOORI:c:\tmpzip\ )
U_MONTASDF - MONTASDFSYSTEMLOAD.PRW(85)

**Comment by amjgfarias** [comment]
problema solucionado.
